repos:
-   repo: local
    hooks:
      - id: isort
        name: isort
        entry: poetry run isort
        language: system
        types: [python]
      - id: black
        name: black
        entry: poetry run black
        language: system
        types: [python]
      - id: pyupgrade
        name: pyupgrade
        entry: poetry run pyupgrade --py37-plus
        language: system
        types: [python]
      - id: mypy
        name: mypy
        entry: poetry run mypy . --exclude tests/
        require_serial: true
        language: system
        types: [python]
        pass_filenames: false
      - id: flake8
        name: flake8
        entry: poetry run flake8
        language: system
        types: [python]
        args: [--config, setup.cfg]
